steps:
- name: 'docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/gcpdevops','.']
- name: "gcr.io/crypto-avatar-385313/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]
- name: "gcr.io/crypto-avatar-385313/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=us-central1-c
  - --cluster=gcp-devops-project
  - --namespace=gcp-devops-prod